apiVersion: entando.org/v1
kind: EntandoDeBundle
metadata:
  name: cms-firegloves-bundle
  labels:
    widget: "true"
    plugin: "true"
    page: "true"
    pageTemplate: "true"
    customLabel: "true"
spec:
  details:
    author: Firegloves
    description: Example Bundle containing CMS components for the Quickstart experience
    dist-tags:
      latest: v0.0.17
    keywords:
      - entando6
    name: Entando Firegloves CMS Bundle
    time:
      created: '2020-06-29T16:17:00.000Z'
      modified: '2020-07-01T08:56:00.000Z'
      v0.0.1: '2020-06-29T16:17:00.000Z'
      v0.0.2: '2020-07-01T08:56:00.000Z'
      v0.0.3: '2020-07-01T09:56:00.000Z'
      v0.0.4: '2020-07-01T10:56:00.000Z'
      v0.0.5: '2020-07-01T11:56:00.000Z'
      v0.0.6: '2020-07-01T12:56:00.000Z'
      v0.0.7: '2020-07-01T13:56:00.000Z'
      v0.0.8: '2020-07-01T14:56:00.000Z'
      v0.0.9: '2020-07-01T15:56:00.000Z'
      v0.0.10: '2020-07-01T16:56:00.000Z'
      v0.0.11: '2020-07-01T17:56:00.000Z'
      v0.0.12: '2020-07-01T18:56:00.000Z'
      v0.0.13: '2020-07-01T19:56:00.000Z'
      v0.0.14: '2020-07-01T20:56:00.000Z'
      v0.0.15: '2020-07-01T20:56:00.000Z'
      v0.0.16: '2020-07-01T20:56:00.000Z'
    versions:
      - v0.0.1
      - v0.0.2
      - v0.0.3
      - v0.0.4
      - v0.0.5
      - v0.0.6
      - v0.0.7
      - v0.0.8
      - v0.0.9
      - v0.0.10
      - v0.0.11
      - v0.0.12
      - v0.0.13
      - v0.0.14
      - v0.0.15
      - v0.0.16
      - v0.0.17
  tags:
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.1
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.2
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.3
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.4
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.5
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.7
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.8
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.9
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.10
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.11
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.12
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.13
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.14
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.15
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.16
    - integrity: ''
      shasum: ''
      tarball: 'https://github.com/firegloves-bundles/entando-cms-quickstart-bundle.git'
      version: v0.0.17